---
volumes:
  grafana-data:
    driver: local
services:
  grafana:
    image: khulnasoft/grafana-oss:10.3.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
